export const PERMISSIONS = {
  MANAGE_ADMIN_STATUS: 'manage-admin-status',
  MANAGE_MODERATOR_STATUS: 'manage-moderator-status',
  MANAGE_ADMIN: 'manage-admin',
  MANAGE_MODERATOR: 'manage-moderator',
  MANAGE_USER: 'manage-user',
  VIEW_USERS: 'view-users',
  VIEW_MODERATORS: 'view-moderators',
  VIEW_ADMINS: 'view-admins',
};

const FIXED_MODERATOR_PERMISSIONS = [
  PERMISSIONS.MANAGE_USER,
  PERMISSIONS.VIEW_MODERATORS,
  PERMISSIONS.VIEW_USERS,
];

export const ASSIGNABLE_MODERATOR_PERMISSIONS = [
  PERMISSIONS.MANAGE_MODERATOR,
  PERMISSIONS.VIEW_ADMINS,
];

export const ROLE_PERMISSIONS = {
  Admin: [
    PERMISSIONS.MANAGE_ADMIN_STATUS,
    PERMISSIONS.MANAGE_MODERATOR_STATUS,
    PERMISSIONS.MANAGE_ADMIN,
    PERMISSIONS.MANAGE_MODERATOR,
    PERMISSIONS.MANAGE_USER,
    PERMISSIONS.VIEW_ADMINS,
    PERMISSIONS.VIEW_MODERATORS,
    PERMISSIONS.VIEW_USERS,
  ],
  Moderator: [...FIXED_MODERATOR_PERMISSIONS, ...ASSIGNABLE_MODERATOR_PERMISSIONS],
  User: [PERMISSIONS.VIEW_MODERATORS, PERMISSIONS.VIEW_USERS],
};
