const PERMISSION_ENUM = {
  MANAGE_ADMIN_STATUS: "manage-admin-status",
  MANAGE_MODERATOR_STATUS: "manage-moderator-status",
  MANAGE_ADMIN: "manage-admin",
  MANAGE_MODERATOR: "manage-moderator",
  MANAGE_USER: "manage-user",
  VIEW_USERS: "view-users",
  VIEW_MODERATORS: "view-moderators",
  VIEW_ADMINS: "view-admins",
};

const FIXED_MODERATOR_PERMISSIONS = [
  PERMISSION_ENUM.MANAGE_USER,
  PERMISSION_ENUM.VIEW_MODERATORS,
  PERMISSION_ENUM.VIEW_USERS,
];

const DYNAMIC_MODERATOR_PERMISSIONS = [
  PERMISSION_ENUM.MANAGE_MODERATOR,
  PERMISSION_ENUM.VIEW_ADMINS,
];

const ROLE_PERMISSIONS = {
  ADMIN: {
    SUPER_ADMIN: [
      PERMISSION_ENUM.MANAGE_ADMIN_STATUS,
      PERMISSION_ENUM.MANAGE_MODERATOR_STATUS,
      PERMISSION_ENUM.MANAGE_ADMIN,
      PERMISSION_ENUM.MANAGE_MODERATOR,
      PERMISSION_ENUM.MANAGE_USER,
      PERMISSION_ENUM.VIEW_ADMINS,
      PERMISSION_ENUM.VIEW_MODERATORS,
      PERMISSION_ENUM.VIEW_USERS,
    ],
    BASIC_ADMIN: [
      PERMISSION_ENUM.MANAGE_MODERATOR_STATUS,
      PERMISSION_ENUM.MANAGE_MODERATOR,
      PERMISSION_ENUM.MANAGE_USER,
      PERMISSION_ENUM.VIEW_ADMINS,
      PERMISSION_ENUM.VIEW_MODERATORS,
      PERMISSION_ENUM.VIEW_USERS,
    ],
  },
  MODERATOR: [...FIXED_MODERATOR_PERMISSIONS],
  USER: [PERMISSION_ENUM.VIEW_MODERATORS, PERMISSION_ENUM.VIEW_USERS],
};

module.exports = {
  ROLE_PERMISSIONS,
  PERMISSION_ENUM,
  FIXED_MODERATOR_PERMISSIONS,
  DYNAMIC_MODERATOR_PERMISSIONS,
};
